# Generated by Django 3.1.1 on 2022-03-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_auto_20220328_1205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
