# Generated by Django 3.1.1 on 2022-03-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_auto_20220328_1304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
